primary_folders:
  - '../mydata/00_working/2022-05-02'
  - '../mydata/00_working/ForensicMedicine'
  - '../mydata/00_working/総合診療部'

secondary_folders:
  - '../mydata/00_working/2022-05-02'
  - '../mydata/00_working/ForensicMedicine'
  - '../mydata/00_working/総合診療部/あ行'
  - '../mydata/00_working/総合診療部/か行'
  - '../mydata/00_working/総合診療部/さ行'
  - '../mydata/00_working/総合診療部/た行'
  - '../mydata/00_working/総合診療部/な行'
  - '../mydata/00_working/総合診療部/は行'
  - '../mydata/00_working/総合診療部/ま行'
  - '../mydata/00_working/総合診療部/や行'
  - '../mydata/00_working/総合診療部/ら行'
  - '../mydata/00_working/総合診療部/わ行'

ignore_extensions:
  - '.tmp'
  - '.log'
  - '.ini'
  - '.db'
  - '.txt'
  - '.text'
  - '.exe'
  - '.dll'
  - '.o'
  - '.obj'
  - '.swp'
  - '.bin'
  - '.cr2'
  - '.ai'
  - '.dat'
  - '.json'
  - '.key'
  - '.pdf'
  - '.pspimage'
  - '.xlsm'

ignore_files:
  - '.DS_Store'
