version: '3.9'
services:
  preprocess:
    image: my-rapids-notebook
    container_name: preprocess
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./mydata:/home/rapids/mydata
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    user: "root"
    working_dir: /home/rapids"
